### ISSUE TITLE
Security Risk: Plain text credentials

### ISSUE THREAD

**Issue by khantiRindani** [excalidraw/excalidraw-libraries#1498]
Hi team,

I've been a huge fan of Excalidraw and have used it extensively. I came across some cool libraries and discovered this repo.

It seems there are plain text credentials in the [file](https://github.com/excalidraw/excalidraw-libraries/blob/main/excalidraw.json). I suppose keeping them as secrets or encrypted environment variables would address the issue.

**Comment by dwelle** [comment]
Hi, that's public and doesn't contain any secrets. It's also no longer used anyway, so should be cleaned up, but we'll be releasing a new version of libraries in the near future so we thought it'd be a waste of time to refactor this repo.

Thanks for keeping an eye though!
