### ISSUE TITLE
add `updated` field

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw-libraries#171]
We should add `updated` and sort by that field (as well). By default should equal `created`.

**Comment by aretecode** [comment]
@dwelle to confirm, do these steps capture the required changes to mark this ticket as `done`?

#### JSON
1. update [`libraries.json`](https://github.com/excalidraw/excalidraw-libraries/blob/main/libraries.json#L810) to rename `date` => `created`
2. update `libraries.json` and add `updated` as another field that is, by default, the value from `created`

#### Markup
3. update [`index.html`](https://github.com/excalidraw/excalidraw-libraries/blob/main/index.html#L160) to change `<p class="updated">Updated: {updated}</p>` => `<p class="updated">Updated: {updated}</p>`

#### Scripting
4. update [`script.js`](https://github.com/excalidraw/excalidraw-libraries/blob/main/script.js#L163) to change the `inner.replace(/updated/)` code to use `created` + `updated`
5. update [`script.js`](https://github.com/excalidraw/excalidraw-libraries/blob/main/script.js#L93) object `sortBy` to add `updated` as an option

**Comment by dwelle** [comment]
Sounds about right. Looks like you've figured it out pretty thoroughly 👍 — feel free to make a PR!

**Comment by aretecode** [comment]
@ferminrp this can be closed now, right?
