### ISSUE TITLE
"Add to Excalidraw" button customisation

### ISSUE THREAD

**Issue by pscanf** [excalidraw/excalidraw-libraries#250]
In [Excalideck](https://excalideck.com/) I just added the possibility to import libraries from https://libraries.excalidraw.com/ . Everything just worked out of the box, which makes me think that loading from other origins != excalidraw.com is considered as a valid use case. If this is the case, it'd be nice to customise the text of the **"Add to Excalidraw"** button (by passing a different product name in the url, probably). In my case for instance, it would say **"Add to Excalideck"**.

![image](https://user-images.githubusercontent.com/3725458/141001652-dc72ad72-dac8-456f-8fb4-d8b3aaea4f52.png)

If this makes sense, I can make a PR for the feature.

**Comment by sohailamjad256** [comment]
can we add excalidraw libraries by calling our own api?

**Comment by sohailamjad256** [comment]
can you send screenshot of your code..like where  you have been changed that button name

**Comment by dwelle** [comment]
@pscanf sorry for the late response. What I propose instead is whitelisting specific apps instead of allowing anyone to write anything in there. Let's start off with Excalidraw, Excalidraw+, and Excalideck: https://github.com/excalidraw/excalidraw-libraries/pull/297

**Comment by pscanf** [comment]
Hey @dwelle, no problem, no hurry. 🙂  Thanks for the feature! I'll implement the counterpart in Excalideck in the coming days.

**Comment by dwelle** [comment]
@pscanf there's actually no counterpart and should work out of the box for your domain. And it does, just checked :).

**Comment by pscanf** [comment]
Ah nice! I thought I'd have to pass the `referrer` param, but ofc it's already passed. 🙂 

I just noticed, `app.excalideck.com` should also be added to the whitelist, I'll make a PR for it now.
