### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [excalidraw/excalidraw-libraries#30]
Hi,<br><br>url : https://github.com/excalidraw/excalidraw-libraries/blob/c4fea10282dc7b91516201c93b29e7ff98e800c9/excalidraw.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by dwelle** [comment]
Hello. All the keys in that json file should be public. We store private secrets outside the codebase.
