### ISSUE TITLE
Add items names for a published library

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw-libraries#313]
How can I add items names to my library?
I just wanted to add fields in JSON, not go through the whole publishing process again.

https://github.com/excalidraw/excalidraw-libraries/blob/main/libraries/inwardmovement/information-architecture.excalidrawlib

**Comment by dwelle** [comment]
That library file is version 1, so you'll need to reexport it. In version 2, you can then add `name` attribute to each item in `"libraryItems"`: 

https://github.com/excalidraw/excalidraw-libraries/blob/e586e5db636617c2f9b8d3a2ebdb0d4629ea0efe/libraries/aleksandr-hovhannisyan/clocks.excalidrawlib#L2720

**Comment by dwelle** [comment]
Closing as resolved?
