### ISSUE TITLE
Bug when resizing grouped shapes

### ISSUE THREAD

**Issue by clementbosc** [excalidraw/excalidraw-libraries#319]
There is a curious bug when resizing grouped shapes : some items are moving on the side whereas they shouldn't.

Normal size : 
![Capture d’écran 2022-01-13 à 12 45 55](https://user-images.githubusercontent.com/9367975/149325122-7924fcd7-8e84-4c29-88ed-0d7199df4fa8.png)

When resizing : 
![Capture d’écran 2022-01-13 à 12 46 02](https://user-images.githubusercontent.com/9367975/149325144-0552d478-d719-4ef8-ad66-1e92af513328.png)

**Comment by dwelle** [comment]
It's more likely related to linear element resizing issues, and is being tracked here: https://github.com/excalidraw/excalidraw/issues/4001. I didn't have an opportunity to dive into this yet :(.
