### ISSUE TITLE
How to update a submitted library? 

### ISSUE THREAD

**Issue by yuelfei** [excalidraw/excalidraw-libraries#413]
such as bugfixes, or new additions. 

Don't know how to create ". excalidawlib"  file.

**Comment by SketchingDev** [comment]
I'm also wondering this. I [recently submitted a library](https://github.com/excalidraw/excalidraw-libraries/pull/443) and would love to keep adding to it.

**Comment by dwelle** [comment]
Hey! Sorry for missing this.

Right now, you'd probably have to make a github PR (by manually exporting the library as `.excalidrawlib`), and that only works for published libraries (which seems to be both of your cases). One downside of this is you'd somehow need to generate the preview PNG manually for the updated library.

If the library hasn't been published yet, then probably the best way is to re-submit, but even that isn't super easy: 1) you'd need to mark the items as unpublished in the editor else it won't allow you to re-publish 2) you can't submit under the same title.

The UX is terrible, and we'll be improving on this!

**Comment by dwelle** [comment]
In the meantime, once we find some pocket of time, we'll make some hacky interim solution to at least allow doing this from the UI.

**Comment by dwelle** [comment]
In the meantime, we've made a fix to allow you to resubmit already "published" library items, so no need to manually remove & add the items into the library just so can you submit again. 

And, if you use the same author and library name as an existing library, the library will be replaced (updated) with your submission. This can be used as a relatively painless update capability.

But, a better workflow than this will come in the future, for sure.

**Comment by SketchingDev** [comment]
That's great, thank you for the update. Also, thank you for such an amazing project!

**Comment by yuelfei** [comment]
Thank you for your replay and excalidraw, I love it.
@[dwelle](https://github.com/dwelle)

**Comment by mwc360** [comment]
@dwelle has the process changed at all over the last 2 years? I.e. if I have a library w/ 60 or so items and I just need to update 1 item, do I still need to republish all 60? I will have to make library updates every month or two so just want to make sure I'm aware of the most efficient process :)

**Comment by felipeavilis** [comment]
I'm about to publish a library but was worried about how to update or add new images. It doesn't seem like a simple thing, but the challenge is part of it.
