### ISSUE TITLE
Docs for creating a library

### ISSUE THREAD

**Issue by Bhupesh-V** [excalidraw/excalidraw-libraries#72]
I have been researching for a while now but I am not able to find any docs on how to create your own library
How does the `excalidrawlib` files are generated? what's the process?

Really appreciate some help here
Thanks

**Comment by dwelle** [comment]
The `.excalidrawlib` is a file generated when you export your library from Excalidraw:

![image](https://user-images.githubusercontent.com/5153846/110367215-adb0a380-8047-11eb-8f3c-1ad41a1b77d9.png)

We should make it clear, for sure.

**Comment by Bhupesh-V** [comment]
Also leading from this.
Is there any way to import SVG files? How are other people creating these libraries, using their mouse?

**Comment by dwelle** [comment]
You can't import SVGs right now (but work is being done in https://github.com/excalidraw/svg-to-excalidraw). What other people do is anything they can come up with :). Mouse, pen, grid mode, etc.

**Comment by Bhupesh-V** [comment]
> You can't import SVGs right now (but work is being done in https://github.com/excalidraw/svg-to-excalidraw). What other people do is anything they can come up with :). Mouse, pen, grid mode, etc.

Oh I see, thanks for the heads up
