### ISSUE TITLE
How to upload custom lib with the extension .excalidrawlib

### ISSUE THREAD

**Issue by hotcoder** [excalidraw/excalidraw-libraries#880]
I have  file with extension .excalidrawlib , how to upload this , so that it will available to everyone or atleast is their any desktop add for excalidraw  , so that i can use that in my local

**Comment by dwelle** [comment]
Hi @hotcoder. You can just import that library file into excalidraw.com and then publish the library following these steps https://github.com/excalidraw/excalidraw-libraries#create-your-own-library 🙏
